# docker-compose.yml
version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /tmp:/tmp
    working_dir: /app
  frontend:
    build: ./frontend/myapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

